%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\SHIBOR.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/21 20:53:31

SlArea='B2:K';
A=size(xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\SHIBOR.xlsx'));
SlArea=[SlArea,int2str(A(1)+1)];

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\SHIBOR.xlsx','Sheet1',SlArea,'',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
dates(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),dates)) = {''};
raw = raw(:,[2,3,4,5,6,7,8,9]);
dates = dates(:,1);

%% Exclude rows with non-numeric cells
I = ~(all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2) & all(cellfun(@isnumeric,dates),2)); % Find rows with non-numeric cells
raw(I,:) = [];
dates(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
SHIBOR_D = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
ON = data(:,1);
OW = data(:,2);
TW = data(:,3);
OM = data(:,4);
TRM = data(:,5);
SIM = data(:,6);
NM = data(:,7);
OY = data(:,8);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% date1=datenum(date1);

%% Extra history data read

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\macbook\Desktop\研究数据\个股\Macrohistory\SHIBOR.xlsx','Sheet1','B2:J2312','',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
dates(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),dates)) = {''};
raw = raw(:,[2,3,4,5,6,7,8,9]);
dates = dates(:,1);

%% Exclude rows with non-numeric cells
I = ~(all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2) & all(cellfun(@isnumeric,dates),2)); % Find rows with non-numeric cells
raw(I,:) = [];
dates(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
SHIBOR_D =[SHIBOR_D;datetime([dates{:,1}].', 'ConvertFrom', 'Excel')];
ON = [ON;data(:,1)];
OW = [OW;data(:,2)];
TW = [TW;data(:,3)];
OM = [OM;data(:,4)];
TRM = [TRM;data(:,5)];
SIM = [SIM;data(:,6)];
NM = [NM;data(:,7)];
OY = [OY;data(:,8)];



%% Clear temporary variables
clearvars data raw dates I SlArea A;