%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\RRR.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/21 23:59:18

SlArea='B2:J';
A=size(xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\RRR.xlsx'));
SlArea=[SlArea,int2str(A(1)+1)];

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\RRR.xlsx','Sheet1',SlArea,'',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
dates(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),dates)) = {''};
raw = raw(:,2);
dates = dates(:,1);

%% Exclude rows with non-numeric cells
I = ~(all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2) & all(cellfun(@isnumeric,dates),2)); % Find rows with non-numeric cells
raw(I,:) = [];
dates(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
RRR = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
now1 = data(:,1);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% date2=datenum(date2);

%% Clear temporary variables
clearvars data raw dates I SlArea A;