%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\macbook\Desktop\研究数据\个股\sample2.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/16 22:22:53

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\macbook\Desktop\研究数据\个股\sample2.xlsx','Sheet1','A2:G169','',@convertSpreadsheetExcelDates);
raw = raw(:,[2,3,4,5,6,7]);
dates = dates(:,1);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
date1 = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
open1 = data(:,1);
high = data(:,2);
close = data(:,3);
low = data(:,4);
volume = data(:,5);
amount = data(:,6);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% date1=datenum(date1);

%% Clear temporary variables
clearvars data raw dates;