%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\MG_SH.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/21 23:30:57

%% Import the data, extracting spreadsheet dates in Excel serial date format

SlArea='B2:J';
A=size(xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\MG_SH.xlsx'));
SlArea=[SlArea,int2str(A(1)+1)];

[~, ~, raw, dates] = xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\MG_SH.xlsx','Sheet1',SlArea,'',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
dates(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),dates)) = {''};
raw = raw(:,[2,3,4,5,6,7]);
dates = dates(:,1);

%% Exclude rows with non-numeric cells
I = ~(all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2) & all(cellfun(@isnumeric,dates),2)); % Find rows with non-numeric cells
raw(I,:) = [];
dates(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names

SHMargin_D = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
rzye = data(:,1);
rzmre = data(:,2);
rqyl = data(:,3);
rqylje = data(:,4);
rqmcl = data(:,5);
rzrqjyzl = data(:,6);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% opDate=datenum(opDate);

%%import extra data

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\macbook\Desktop\研究数据\个股\Macrohistory\MG_SH.xlsx','Sheet1','B2:H1400','',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
dates(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),dates)) = {''};
raw = raw(:,[2,3,4,5,6,7]);
dates = dates(:,1);

%% Exclude rows with non-numeric cells
I = ~(all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2) & all(cellfun(@isnumeric,dates),2)); % Find rows with non-numeric cells
raw(I,:) = [];
dates(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
SHMargin_D = [SHMargin_D;datetime([dates{:,1}].', 'ConvertFrom', 'Excel')];
rzye = [rzye;data(:,1)];
rzmre =[rzmre; data(:,2)];
rqyl = [rqyl;data(:,3)];
rqylje =[rqylje; data(:,4)];
rqmcl =[rqmcl; data(:,5)];
rzrqjyzl =[rzrqjyzl; data(:,6)];

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% opDate1=datenum(opDate1);

%% Clear temporary variables
clearvars data raw dates I A SlArea;