%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\SH_INDEX.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/28 20:40:26

SlArea='A2:G';
A=size(xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\SH_INDEX.xlsx'));
SlArea=[SlArea,int2str(A(1)+1)];

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread('C:\Users\macbook\Desktop\研究数据\个股\AutoMacro\SH_INDEX.xlsx','Sheet1',SlArea,'',@convertSpreadsheetExcelDates);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
dates(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),dates)) = {''};

raw = raw(:,[2,3,4,5,6,7]);
dates = dates(:,1);

%% Exclude rows with non-numeric cells
I = ~(all(cellfun(@(x) (isnumeric(x) || islogical(x)) && ~isnan(x),raw),2) & all(cellfun(@isnumeric,dates),2)); % Find rows with non-numeric cells
raw(I,:) = [];
dates(I,:) = [];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
SH_date = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
SH_open = data(:,1);
SH_high = data(:,2);
SH_close = data(:,3);
SH_low = data(:,4);
SH_volume = data(:,5);
SH_amount = data(:,6);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% date1=datenum(date1);

%% Clear temporary variables
clearvars data raw dates I SlArea A;